Login/config/routes.rb
Rails.application.routes.draw do
  
  resources :friend_ships
  get 'friendships/create'
  get 'friendships/destroy'
  resources :likes
  resources :comments
  resources :posts
  root 'static_pages#home'
  
  resources :users, except: [:new],path:'usuarios'
  
  get '/cadastro',to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    resources :friend_ships    
    resources :posts do
      resources :comments
      resources :likes
    end
  end
end

Login/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  
  
end

Login/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SessionsHelper
  before_action :current_user
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id=@current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

Login/app/helpers/posts_helper.rb
module PostsHelper
end

Login/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Login/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Voltar', @post %>

Login/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

Login/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_path(@current_user) %>

Login/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Segundo:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post.content %>
</p>

<!--permirtir somente o usuario usar o edit-->
<% if @post.user==current_user%>
  <%= link_to 'Edit', edit_post_path(@post) %> <br>
<% end %>

<%= link_to 'Back', user_path(@current_user)%>
<br>
<%= link_to  "fazer um comentario", user_post_comment_path(@post.user_id,@post,:new) %>

<%@vari= @post.likes.find_by user_id:@current_user%>

<!--curtir somente uma vez-->
<%if @vari.nil?%>
  <%=link_to 'curtir',user_post_like_path(@post.user_id,@post,:new) %>

<%end%>

<p>esse post tem <%=@post.likes.length%> curtida(s)</p>
<p>esse post tem <%=@post.comments.length%> comentario(s)</p>

<br>
<p> comentarios </p>
<!--colocar o comment dando permissao para destruir somente se for o dono do comment-->

<%@post.comments.each do |comment|%>
  
  <%@aux=User.find_by id: comment.user_id%>
  <p> Segundo <%=@aux.name%></p>
  <p><%=comment.content%></p>
  <%if @current_user.id == comment.user_id%>
        <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%end%>
  
<%end%>