Login/config/routes.rb
Rails.application.routes.draw do
  
  resources :friend_ships
  get 'friendships/create'
  get 'friendships/destroy'
  resources :likes
  resources :comments
  resources :posts
  root 'static_pages#home'
  
  resources :users, except: [:new],path:'usuarios'
  
  get '/cadastro',to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    resources :friend_ships    
    resources :posts do
      resources :comments
      resources :likes
    end
  end
end

Login/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts
    has_many :comments
    has_many :likes
    validates :password, presence: true,length: {minimum: 6 }
    has_many :friendships
    has_many :friends, :through => :friendships    
end 

Login/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :impede_nao_logado,except: [:new,:create]
    before_action :impede_logado,only: [:new]

    def new
        @user =User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to @user
        else
            render 'new'
        end
    end

    def index
    end

    def show
        @user=User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def impede_nao_logado
        if !logged_in?
            redirect_to root_path
        end
    end
    
    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end
    
end

Login/app/helpers/users_helper.rb
module UsersHelper
end

Login/app/views/users/_form.html.erb
<%= form_with(model: user,local: true) do |form| %>
    <div class="field">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name %>
    </div>

    <div class="field">
        <%= form.label :email, "E-mail" %>
        <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :password, "Senha"%>
        <%= form.password_field :password %> 
    </div>

    <div class="field">
        <%= form.label :password_confirmation,"Confimar sua senha" %>
        <%= form.password_field :password_confirmation %>
    </div>

    <div class="action">
        <%= form.submit "Cadastrar" %>
    </div>
<% end %>

Login/app/views/users/index.html.erb
<% @users=User.all %>

<br>
<% for user in (@users)%>
    <tr>
        <%if user != @current_user%>
        <td><%= user.name %></td>
        <td> <%= link_to  "Ver perfil", user_path(user) %></td>
        
        <br>
        <% end %>
        
    <tr>
<% end %>
<br>
<%= link_to  "back", user_path(@current_user) %>

Login/app/views/users/new.html.erb
<h1>Cadastre-se</h1>
<%= render 'form', user:@user %>

Login/app/views/users/show.html.erb
<% if logged_in? && @user==current_user%>
    <%= link_to  "Sair", logout_path,method: :delete %>
  <%else%>
  <%= link_to  "Voltar para seu perfil", user_path(current_user)%>  
<%end%>

<br><%= @user.name %><br>
<%= @user.email %>
<%if @user==current_user%>
    <%=link_to 'Crie um novo post',user_post_path(@user,:new)%>

    
<% end %>
<p>POST:</p> 
<% for post in (@user.posts)%>
<br>   
    <p> De: <%= post.user.name %></p>

    <tr>    
        
        
        <td><%= post.content %></td>
        <br>
        <td><%= link_to 'Ver mais sobre este post', user_post_path(@user,post) %></td>
        
      </tr>
<%end%>
<br>
<br>
<%= link_to  "Outros usuarios", users_path %>
<% @teste=true %>
<p>Amigos</p>


<% for friend in FriendShip.where user_id: @user.id%>
    <% if (User.find(friend.friend_id)==@current_user)%>
        <%@teste=false%>
        
    <% end %>
    
    <%=User.find(friend.friend_id).name%>
    <% if @user==@current_user%>
        <%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <br>
<%end%>

<!--lista os amigos e impedir de fazer amizade com um amigo e com si proprio-->

<% for friend in FriendShip.where friend_id: @user.id%>
    
    <% if (User.find(friend.user_id)==@current_user)%>
        <% @teste=false%>
        
    <% end %>


    <%=User.find(friend.user_id).name%>
    <% if @user==@current_user%>
        <%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <br>
<%end%>
<% if ((@user!=@current_user)&&(@teste))%>
<br>
    <%= link_to "Adicionar aos amigos",user_friend_ships_path(@user,:new) %> 

<%end%>