Login/config/routes.rb
Rails.application.routes.draw do
  
  resources :friend_ships
  get 'friendships/create'
  get 'friendships/destroy'
  resources :likes
  resources :comments
  resources :posts
  root 'static_pages#home'
  
  resources :users, except: [:new],path:'usuarios'
  
  get '/cadastro',to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    resources :friend_ships    
    resources :posts do
      resources :comments
      resources :likes
    end
  end
end

Login/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
end

Login/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include SessionsHelper
  before_action :current_user
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :show, only: [:create]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    post_id=params[:id]
    @post=Post.find_by id: post_id
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id=@current_user.id
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :content)
    end
end

Login/app/helpers/comments_helper.rb
module CommentsHelper
end

Login/app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  
  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Login/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', post_path(@comment.post_id)%>

Login/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.post %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

Login/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', user_path(current_user) %>

Login/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user.name %>
</p>


<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', user_path(current_user) %>